@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Person" as person PERSON_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "deleteattribute /uuid 1234 /name1 /name2"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("deleteattribute /uuid 1234 /name1 /name2")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : findPerson(uuid)
activate model MODEL_COLOR

model --[MODEL_COLOR]> logic : return person object
deactivate model

loop for each attribute
    logic -[LOGIC_COLOR]> person : hasAttribute(attributeName)
    activate person PERSON_COLOR

    person --[PERSON_COLOR]> logic : return true if exists
    deactivate person

    logic -[LOGIC_COLOR]> person : deleteAttribute(attributeName)
    activate person PERSON_COLOR
    person --[PERSON_COLOR]> logic : attribute deleted
    deactivate person
end
destroy person

logic -[LOGIC_COLOR]> storage : saveAddressBook(addressBook)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
storage --[STORAGE_COLOR]> storage : file saved
deactivate storage STORAGE_COLOR_T1

storage --[STORAGE_COLOR]> logic : save complete
deactivate storage
storage --[HIDDEN]> storage :
destroy storage

logic --[LOGIC_COLOR]> ui : CommandResult("Attributes deleted successfully.")
deactivate logic

ui--[UI_COLOR]> user : display "Attributes deleted successfully."
deactivate ui
@enduml
